modLoader="javafml"
loaderVersion="${neoforge_loader_version_range}"
issueTrackerURL = "${issues}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="Bovines and Buttercups"
logoFile="${mod_id}.png"
logoBlur=false
updateJSONURL = "https://api.modrinth.com/updates/BDg6nMn3/forge_updates.json"
authors="${mod_author}"
credits="${mod_contributors}"
description='''
${mod_description}
'''

[[mixins]]
config = "${mod_id}.mixins.json"
[[mixins]]
config = "${mod_id}.neoforge.mixins.json"

[[accessTransformers]]
file="${mod_id}.cfg"

[[dependencies.${mod_id}]]
modId="neoforge"
mandatory=true
versionRange="${neoforge_loader_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="${neoforge_minecraft_version_range}"
ordering="NONE"
side="BOTH"